# supports: 'shibuya', 'shiden', 'astar', 'aleph-zero-testnet'
archive: shibuya
target:
  type: postgres
contracts:
  - name: testToken
    abi: "./abi/erc20.json"
    address: "0x5207202c27b646ceeb294ce516d4334edafbd771f869215cb070ba51dd7e2c72"
    events:
      - Transfer